### Importing required libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("C:/Users/Swati Panchal/Downloads/pubg_data_full.csv")

C:\Users\Swati Panchal\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,32,33,34,35,36,37,39,40,41,44,45,46,47) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
data.head()

Id  groupId matchId assists boosts damageDealt DBNOs headshotKills heals  \
0  0       24       0       0      5       247.3     2             0     4   
1  1   440875       1       1      0       37.65     1             1     0   
2  2   878242       2       0      1       93.73     1             0     2   
3  3  1319841       3       0      0       95.88     0             0     0   
4  4  1757883       4       0      1         0.0     0             0     1   

  killPlace  ... Unnamed: 38 Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42  \
0        17  ...         NaN         NaN         NaN         NaN         NaN   
1        45  ...         NaN         NaN         NaN         NaN         NaN   
2        54  ...         NaN         NaN         NaN         NaN         NaN   
3        86  ...         NaN         NaN         NaN         NaN         NaN   
4        58  ...         NaN         NaN         NaN         NaN         NaN   

  Unnamed: 43 Unnamed: 44 Unnamed: 45 Unnamed: 46 Unnamed: 47  
0         NaN         NaN         NaN         NaN         NaN  
1         NaN         NaN         NaN         NaN         NaN  
2         NaN         NaN         NaN         NaN         NaN  
3         NaN         NaN         NaN         NaN         NaN  
4         NaN         NaN         NaN         NaN         NaN  

[5 rows x 48 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146987 entries, 0 to 146986
Data columns (total 48 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   Id               146987 non-null  object 
 1   groupId          146987 non-null  object 
 2   matchId          146987 non-null  object 
 3   assists          146987 non-null  object 
 4   boosts           146987 non-null  object 
 5   damageDealt      146987 non-null  object 
 6   DBNOs            146987 non-null  object 
 7   headshotKills    146987 non-null  object 
 8   heals            146987 non-null  object 
 9   killPlace        146987 non-null  object 
 10  killPoints       146986 non-null  object 
 11  kills            146986 non-null  object 
 12  killStreaks      146985 non-null  object 
 13  longestKill      146985 non-null  object 
 14  maxPlace         146985 non-null  object 
 15  numGroups        146984 non-null  object 
 16  revives          146984 non-null  obje

### Dropping the unnecessary columns which have almost null values

In [5]:
data.drop(data.columns[26:],axis=1,inplace=True)

In [6]:
data.head()

Id  groupId matchId assists boosts damageDealt DBNOs headshotKills heals  \
0  0       24       0       0      5       247.3     2             0     4   
1  1   440875       1       1      0       37.65     1             1     0   
2  2   878242       2       0      1       93.73     1             0     2   
3  3  1319841       3       0      0       95.88     0             0     0   
4  4  1757883       4       0      1         0.0     0             0     1   

  killPlace  ... revives rideDistance roadKills swimDistance teamKills  \
0        17  ...       1        591.3         0          0.0         0   
1        45  ...       0          0.0         0          0.0         0   
2        54  ...       1          0.0         0          0.0         0   
3        86  ...       0          0.0         0          0.0         0   
4        58  ...       0          0.0         0          0.0         0   

  vehicleDestroys walkDistance weaponsAcquired winPoints winPlacePerc  
0               0        782.4               4      1458       0.8571  
1               0        119.6               3      1511         0.04  
2               0       3248.0               5      1583       0.7407  
3               0        21.49               1      1489       0.1146  
4               0        640.8               4      1475       0.5217  

[5 rows x 26 columns]

In [7]:
data.isnull().sum()

Id                   0
groupId              0
matchId              0
assists              0
boosts               0
damageDealt          0
DBNOs                0
headshotKills        0
heals                0
killPlace            0
killPoints           1
kills                1
killStreaks          2
longestKill          2
maxPlace             2
numGroups            3
revives              3
rideDistance         3
roadKills            3
swimDistance         5
teamKills           12
vehicleDestroys     36
walkDistance        72
weaponsAcquired    128
winPoints          192
winPlacePerc       234
dtype: int64

In [8]:
data.shape

(146987, 26)

### Observing the data that how many unique values are there

In [9]:
for i in data.columns:
    print(i)
    print(data[i].unique())
    print(data[i].unique().shape[0], data[i].shape[0], "\n")

Id
[0 1 2 ... 208824 208825 208826]
146973 146987 

groupId
[24 440875 878242 ... 1429567 1430909 1431822]
99969 146987 

matchId
[0 1 2 ... '18267' '18268' '18269']
64066 146987 

assists
[0 1 2 3 4 7 5 6 8 12 13 10 9 16 '0' '3' '1' '2' '5' '4' '6' '7' '9' '0(0'
 '28.65' '100' '8' '225.5�1' '56*79' '0�0<0' '0\x0c0' '0l0' '3-Jan'
 '2-Mar' 'p<0$0' '�' '27' '0-0' '105.7' '0��' '0&0' ' ' '1l0' '1-Feb'
 '�<<L589.7' '0<0' '1(0' '495.6' '108.9' '\x11.1' '0\x0c4' '0L0' '54.81'
 '1<2' '0(1' '0$2' '14' '10' 15 11]
60 146987 

boosts
[5 0 1 2 3 6 4 10 9 8 7 12 11 13 14 '0' '5' '1' '2' '7' '3' '4' '6' '9'
 '8' '110' '0$0' '2\x12.49' '900' '0(100' '0-0' '\x10' '332.3' '4�.68'
 '0.1' '438.6' '77.33' '2(49<.5' '0\x0c ' '2$1\x140.6' '43' '77.71' '�'
 '74*65' '8=.\x16' 's' '4-109.5' '28.3' '0$=9.v2' '100$3' '2238' '1 0'
 '123.2' '24.37' '3l373.3' '54.87' '2.70\x0e81' '800.5<7-3' '1637'
 '2 191.6$1(1' '050.?' '615.6' '0�169.5' '42.56' '1459$18$5' '100' '34.32'
 '47.88$0' '0(0' '1\x168.�' '21.6' '339.6'

24579 146987 

maxPlace
[29 26 28 97 47 96 44 46 25 98 30 92 27 19 50 42 23 20 45 94 35 49 22 21
 48 24 88 31 8 5 13 11 93 99 87 6 95 7 43 12 15 32 33 3 69 38 14 17 9 90
 89 85 70 100 91 10 41 40 84 18 4 16 34 75 68 82 39 37 36 74 2 65 83 61 86
 58 80 79 71 73 55 78 72 53 81 54 76 77 51 60 64 56 52 1 66 67 59 62 0
 '29' '22' '27' '98' '49' '48' '28' '50' '21' '26' '25' '88' '96' '44'
 '47' '43' '75' '19' '30' '31' '23' '97' '13' '92' '95' '46' '84' '20'
 '33' '32' '18' '4' '94' '45' '40' '41' '11' '100' '24' '10' '68' '90'
 '91' '82' '42' '8' '39' '93' '6' '16' '99' '87' '12' '14' '37' '89' '36'
 '5' '17' '34' '85' '74' '2' '65' '3' '83' '61' '7' '0' '47$0' '1'
 '0\x0c0' '19l0' '4�0' nan '0h1898.2' '0�43.51.0' '2=' 'p' '0(0' 'y3'
 '964&3' '7%' '0l0' '38' '22<0' '226.8' '20.2' '3p' '�' '!' '252.:'
 '\x10(144\x17' '2%�25.0' '30.0(0' '0.0$0' '0-0' '�043' '0$8' '382.7'
 '1,19,2,846.2,0,0,�,0,1296,5,1500,0n9\r\x02w1811l115105883619,0,0,284.3,:,0 0,3\x16,1659,1,5,5/824,30,30,0,0,0,0,0,0,78.2

[782.4 119.6 3248.0 ... 57.84 94.8 5.611]
31978 146987 

weaponsAcquired
[4 3 5 1 9 2 6 7 8 0 29 12 14 10 11 28 22 18 21 20 15 16 37 32 24 13 19 33
 26 27 40 38 61 60 17 25 23 35 34 49 30 31 36 41 47 50 '0' '3' '4' '1' '2'
 '6' '5' '7' '8' '10' '14' '24' '11' '21' '9' '12' '18' '22' '16' '13'
 '15' '20' '26' '25' '31' '3l1504' '0.(542' '0.\x181<2' nan '0.4769'
 '0.2308' '0.0638' '0.8696-' '!594' '0.7308' '62.09' '1450' '1500'
 '0.28(9' '0.2593' '�49&' '0&5385' '0.8161' '1532' '0.8\x1283' '42' '1440'
 '!533$0.52' '0.2222' '0.)286' '1<�4' '4(1499' '1498' '�' '\x14.4583'
 '0<0\x0c0l629.1' '0.75' '2.479�' '0�1633' '1522' '2<1519' '1157118' '>'
 '0.1333' '0.4:31' '0.2385' '1547' '14<7' '14y6' '0.25' '0.3214' '0.85!9'
 '1420' '0.3696' '0.75\t' '3.1506' '15�6' '0.963' '0.7037' '1497' '1568'
 '1512' '0.9259' '1503-0.0208' '0.2963' '0.6538' '481' '1525' '148;'
 '0.965\x15' '0.73p8' '0.4683' '0.0769' '1448' '0.8854' '28' '4.2043'
 '1675' '0.1923' '1514' '0.088)\t' '0.5204' '0.3125' '0.3846' '0.7

### Handling the noisy data and inconsistent data

In [10]:
for i in data.columns:
    data[i] = data[i].astype(str)
    data[i] = data[i].str.replace(r'\W|\D|',"")
    data[i] = data[i].replace('', np.nan, regex=True)
    data[i] = data[i].astype(float,errors="ignore")
    data[i] = data[i].replace([np.inf, -np.inf], np.nan)

C:\Users\Swati Panchal\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  This is separate from the ipykernel package so we can avoid doing imports until


### Observing the unique data in each column after handling inconsistent and noisy data

In [11]:
for i in data.columns:
    print(i)
    print(data[i].unique())
    print(data[i].unique().shape[0], data[i].shape[0], "\n")

Id
[0.00000e+00 1.00000e+00 2.00000e+00 ... 2.08824e+05 2.08825e+05
 2.08826e+05]
146907 146987 

groupId
[2.400000e+01 4.408750e+05 8.782420e+05 ... 1.429567e+06 1.430909e+06
 1.431822e+06]
87388 146987 

matchId
[0.00000000e+000 1.00000000e+000 2.00000000e+000 ... 5.40844239e+227
 6.40650480e+007             nan]
47740 146987 

assists
[0.0000e+00 1.0000e+00 2.0000e+00 3.0000e+00 4.0000e+00 7.0000e+00
 5.0000e+00 6.0000e+00 8.0000e+00 1.2000e+01 1.3000e+01 1.0000e+01
 9.0000e+00 1.6000e+01 2.8650e+03 1.0000e+02 2.2551e+04 5.6790e+03
        nan 2.7000e+01 1.0570e+03 5.8970e+03 4.9560e+03 1.0890e+03
 5.4810e+03 1.4000e+01 1.5000e+01 1.1000e+01]
28 146987 

boosts
[5.000000e+00 0.000000e+00 1.000000e+00 2.000000e+00 3.000000e+00
 6.000000e+00 4.000000e+00 1.000000e+01 9.000000e+00 8.000000e+00
 7.000000e+00 1.200000e+01 1.100000e+01 1.300000e+01 1.400000e+01
 1.100000e+02 2.490000e+02 9.000000e+02 1.000000e+02          nan
 3.323000e+03 4.680000e+02 4.386000e+03 7.733000e+03 2.495000e+

[8.571e+03 4.000e+00 7.407e+03 ... 5.309e+03 7.439e+03 4.912e+03]
1837 146987 



### Missing values 

In [12]:
for i in data.columns:
    print(i.ljust(20) , data[i].isnull().sum())

Id                   0
groupId              1
matchId              1
assists              3
boosts               13
damageDealt          6
DBNOs                20
headshotKills        13
heals                3
killPlace            3
killPoints           7
kills                11
killStreaks          13
longestKill          8
maxPlace             11
numGroups            12
revives              17
rideDistance         19
roadKills            12
swimDistance         18
teamKills            21
vehicleDestroys      37
walkDistance         74
weaponsAcquired      132
winPoints            192
winPlacePerc         235


### Handling the Missing values using Random Sample Imputation

In [13]:
def impute(df,col):
    for i in col:
        random_sample = df[i].dropna().sample(df[i].isnull().sum(),random_state=42)
        random_sample.index = df[df[i].isnull()].index
        df.loc[df[i].isnull(),i] = random_sample

In [14]:
impute(data,data.columns)

In [15]:
data.isnull().sum()

Id                 0
groupId            0
matchId            0
assists            0
boosts             0
damageDealt        0
DBNOs              0
headshotKills      0
heals              0
killPlace          0
killPoints         0
kills              0
killStreaks        0
longestKill        0
maxPlace           0
numGroups          0
revives            0
rideDistance       0
roadKills          0
swimDistance       0
teamKills          0
vehicleDestroys    0
walkDistance       0
weaponsAcquired    0
winPoints          0
winPlacePerc       0
dtype: int64

### Converting the columns to their necessary datatypes

In [16]:
col = data.columns.drop(['damageDealt','longestKill','rideDistance','swimDistance','walkDistance','winPlacePerc'])
col

Index(['Id', 'groupId', 'matchId', 'assists', 'boosts', 'DBNOs',
       'headshotKills', 'heals', 'killPlace', 'killPoints', 'kills',
       'killStreaks', 'maxPlace', 'numGroups', 'revives', 'roadKills',
       'teamKills', 'vehicleDestroys', 'weaponsAcquired', 'winPoints'],
      dtype='object')

In [17]:
data[col] = data[col].apply(np.floor).astype(int)

### Finally we have cleaned our data and now its ready for preprocessing

In [18]:
data.isnull().sum().sum()

0

In [19]:
data.dtypes

Id                   int32
groupId              int32
matchId              int32
assists              int32
boosts               int32
damageDealt        float64
DBNOs                int32
headshotKills        int32
heals                int32
killPlace            int32
killPoints           int32
kills                int32
killStreaks          int32
longestKill        float64
maxPlace             int32
numGroups            int32
revives              int32
rideDistance       float64
roadKills            int32
swimDistance       float64
teamKills            int32
vehicleDestroys      int32
walkDistance       float64
weaponsAcquired      int32
winPoints            int32
winPlacePerc       float64
dtype: object

In [20]:
data.head(10)

Id  groupId  matchId  assists  boosts  damageDealt  DBNOs  headshotKills  \
0   0       24        0        0       5       2473.0      2              0   
1   1   440875        1        1       0       3765.0      1              1   
2   2   878242        2        0       1       9373.0      1              0   
3   3  1319841        3        0       0       9588.0      0              0   
4   4  1757883        4        0       1          0.0      0              0   
5   5  2200824        5        0       2       1281.0      0              0   
6   6  2568717        6        1       0       1303.0      0              0   
7   7  2612473        7        1       1       6618.0      2              3   
8   8  2656377        8        0       3       9472.0      0              0   
9   9  2700597        9        0       0       1376.0      0              0   

   heals  killPlace  ...  revives  rideDistance  roadKills  swimDistance  \
0      4         17  ...        1        5913.0          0           0.0   
1      0         45  ...        0           0.0          0           0.0   
2      2         54  ...        1           0.0          0           0.0   
3      0         86  ...        0           0.0          0           0.0   
4      1         58  ...        0           0.0          0           0.0   
5      0         25  ...        0       22210.0          0           0.0   
6      0         28  ...        0        7217.0          0           0.0   
7      2          3  ...        0           0.0          0           0.0   
8      5         50  ...        0       29630.0          0         289.0   
9      0         81  ...        0           0.0          0           0.0   

   teamKills  vehicleDestroys  walkDistance  weaponsAcquired  winPoints  \
0          0                0        7824.0                4       1458   
1          0                0        1196.0                3       1511   
2          0                0       32480.0                5       1583   
3          0                0        2149.0                1       1489   
4          0                0        6408.0                4       1475   
5          0                0       10160.0                4       1500   
6          0                0        2801.0                3       1495   
7          0                0       26170.0                4       1479   
8          0                0       31390.0                5       1528   
9          0                0        2387.0                3       1500   

   winPlacePerc  
0        8571.0  
1           4.0  
2        7407.0  
3        1146.0  
4        5217.0  
5        9368.0  
6        3721.0  
7          10.0  
8        7037.0  
9         417.0  

[10 rows x 26 columns]

In [22]:
data.isnull().sum().sum()

0